from data_structures import plan, task, action, item


def findMismatch(actualPlan: plan, expectedPlan: plan):
    """Function to find the mismatch between the actual plan and the expected plan.

    Args:
    - actualPlan: The plan generated by the robot.
    - expectedPlan: The plan that was expected to be executed by the robot.

    Returns:
    - A list of mismatches found between the two plans.
    """

    mismatches = []

    # Compare tasks in both plans
    for actual_task, expected_task in zip(actualPlan.tasks, expectedPlan.tasks):
        if actual_task.description != expected_task.description:
            mismatches.append(f"Task mismatch: Expected '{expected_task.description}', but got '{actual_task.description}'")

        # Compare actions within each task
        for actual_action, expected_action in zip(actual_task.actions,
                                                  expected_task.actions):
            if actual_action.description != expected_action.description:
                mismatches.append(f"Action mismatch in task '{actual_task.description}': Expected '{expected_action.description}', but got '{actual_action.description}'")

    return mismatches
